[metadata]
name = facturxlib
version = attr:facturxlib.__version__
; url = https://github.com/kbr/autocron
; project_urls =
;     Homepage = https://github.com/kbr/autocron
;     Code = https://github.com/kbr/autocron
;     Issue tracker = https://github.com/kbr/autocron/issues
description = Library to create Factur-X conform CrossIndustryInvoice xml-files.
; long_description = file: README.md
; long_description_content_type = text/markdown
license = MIT
; license_file = LICENSE
author = Klaus Bremer
author_email = bremer@bremer-media.com
platform = any
keywords = Factur-X, ZUGFerd, CrossIndustryInvoice, xml, generator
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Utilities

[options]
packages = facturxlib

; [options.entry_points]
; console_scripts =
;     autocron = autocron.admin:main
